### PR TITLE
TCP mode

### PR DESCRIPTION
**Pull request by Pentiumluyu**
Send packets with forged TCP headers to avoid qos.
**Caveat:**
 -  Because the program sends SYN/ACK packets with payloads without establishing TCP connection in this mode, some VPS providers may treat this behavior as DDoS attacks.

### CODE REVIEW

**Comment by clowwindy** [comment]
Seems there're conflicts in the pull request.

**Comment by Pentiumluyu** [comment]
Oh, because I created the branch on May 13. I will rebase and re-edit the repo.

**Comment by hdid** [comment]
@Pentiumluyu 
any update?

**Comment by Pentiumluyu** [comment]
Did you find some bugs? @hdid

**Comment by hdid** [comment]
i could not build it for windows:

vpn.c:58:25: fatal error: netinet/tcp.h: No such file or directory
 #include <netinet/tcp.h>
                         ^
compilation terminated.
Makefile:536: recipe for target 'vpn.lo' failed
make[3]: *** [vpn.lo] Error 1
make[3]: Leaving directory '/usr/src/ShadowVPN/src'
Makefile:556: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/usr/src/ShadowVPN/src'
Makefile:388: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/src/ShadowVPN'
Makefile:319: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Pentiumluyu** [comment]
I haven't complied in Cygwin and Darwin. I'll try to fix that.

**Comment by clowwindy** [comment]
@Pentiumluyu I've added you to collaborators, you can push to the `tcp` branch directly.

**Pull request merged**
