### PR TITLE
Add TCP mode(fake TCP header)

### PR DESCRIPTION
**Pull request by Pentiumluyu**
* Use RAW_SOCK to send self constructed packet.
* Use [libnetfilter_queue] to receive and drop fake TCP packet.
[libnetfilter_queue]: https://home.regit.org/netfilter-en/using-nfqueue-and-libnetfilter_queue/

### CODE REVIEW

**Comment by yy1984** [comment]
then can use net-speeder  to speed up shadowvpn ?

**Comment by Pentiumluyu** [comment]
No need. But you can.

**Comment by clowwindy** [comment]
I don't have much time to look at the code recently. You can try to fix the unit test and do some performance test at the moment.

Thanks for the great work!

**Comment by Pentiumluyu** [comment]
Performance looks good. I have to use libnetfilter_queue to drop packets on the vps, otherwise the vps will send rst. I wonder if using lower level socket to drop packets would yield better performance?

**Comment by clowwindy** [comment]
One possible way that we can use raw sockets to receive these TCP packets without sending RST is to add a filter rule in the iptables.

The main reason to use fake TCP is to solve the QoS problem. So we can compare the download speed in an Internet environment.

**Comment by Pentiumluyu** [comment]
The phenomenon I observed on DO: When using raw socket, if the program just recv, nothing happen. But if the program try to send something back, a rst packet without data would be sent. Would iptables work any way?
I haven't done speed test yet. But I can use some ports that were originally blocked now, like 1123.

**Comment by clowwindy** [comment]
I think you can try to add a DROP rule on both sides in the OUTPUT chain.

**Comment by clowwindy** [comment]
I created a `tcp` branch. Could you please submit a pull request to that branch instead? I think we can have more people to test TCP mode.

**Comment by Pentiumluyu** [comment]
Ok, I will submit a pull request tonight.

**Pull request closed without merging**
